# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8edf2c57fdd17e168911ccd5b614d232752e3f58a617fb06aae02d53fe880fff100a358855608859a8f6fb96ebf8010cda2e342fa10887f07974e35bda0dd37a

test:
  secret_key_base: bcfff3a2447fdd75abdafe7ef6eb2b388b7c24eb8bec84cead28c684ba016cd15252c6268d72e0c5f88dd1b7cce7fb079b2c29481c76d1d200e988bb8e9d458b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
